name: Deploy to AWS S3

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AKIAU6GDZ5WNVAMRQVNX }}
          aws-secret-access-key: ${{ secrets.lTpKrxkYAnuoWE7WGnkLM5usfJdCIqqdI/QNCigl }}
          aws-region: us-west-2

      - name: Deploy to S3
        run: aws s3 sync ./build s3://quizwebsite1340 
